# Generated by Django 5.2.1 on 2025-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('tamano', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=100)),
                ('salud', models.CharField(max_length=200)),
                ('vacunado', models.BooleanField(default=False)),
                ('estado_de_adopcion', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=10)),
                ('temperamento', models.CharField(max_length=200)),
            ],
        ),
    ]
