# Generated by Django 5.2.1 on 2025-05-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopdog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('preferencia_raza', models.CharField(blank=True, max_length=50, null=True)),
                ('preferencia_edad', models.CharField(blank=True, choices=[('cachorro', 'Cachorro'), ('joven', 'Joven'), ('adulto', 'Adulto')], max_length=10, null=True)),
                ('preferencia_tamano', models.CharField(blank=True, choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10, null=True)),
                ('histo_adop', models.ManyToManyField(blank=True, to='adopdog.perro')),
            ],
        ),
    ]
